export const CAVITE_CITY_TO_BARANGAYS = {
  "General Trias": [
    "Alingaro",
    "Arnaldo Pob. I",
    "Arnaldo Pob. II",
    "Bagumbayan Pob.",
    "Bacao I",
    "Bacao II",
    "Biclatan",
    "Buenavista I",
    "Buenavista II",
    "Buenavista III",
    "Corregidor Pob.",
    "Dulong Bayan Pob.",
    "Gov. Ferrer",
    "Javalera",
    "Manggahan",
    "Navarro",
    "Ninety Sixth Pob.",
    "Panungyanan",
    "Pasong Camachile I",
    "Pasong Camachile II",
    "Pasong Kawayan I",
    "Pasong Kawayan II",
    "Pinagtipunan",
    "Prinza Pob.",
    "Sampalucan Pob.",
    "San Francisco",
    "San Gabriel Pob.",
    "San Juan I",
    "San Juan II",
    "Santa Clara",
    "Tapia",
    "Tejero",
    "Vibora Pob."
  ],
  "Imus": [
    "Alapan I-A",
    "Alapan I-B",
    "Alapan I-C",
    "Alapan II-A",
    "Alapan II-B",
    "Anabu I-A",
    "Anabu I-B",
    "Anabu I-C",
    "Anabu II-A",
    "Anabu II-B",
    "Anabu II-C",
    "Anabu II-D",
    "Anabu II-E",
    "Anabu II-F",
    "Bagong Silang",
    "Bayan Luma I",
    "Bayan Luma II",
    "Bayan Luma III",
    "Bayan Luma IV",
    "Bayan Luma V",
    "Bayan Luma VI",
    "Bayan Luma VII",
    "Bayan Luma VIII",
    "Bayan Luma IX",
    "Bucandala I",
    "Bucandala II",
    "Bucandala III",
    "Bucandala IV",
    "Bucandala V",
    "Bucandala VI",
    "Bucandala VII",
    "Bucandala VIII",
    "Carsadang Bago I",
    "Carsadang Bago II",
    "Magdalo",
    "Maharlika",
    "Malagasang I-A",
    "Malagasang I-B",
    "Malagasang I-C",
    "Malagasang I-D",
    "Malagasang I-E",
    "Malagasang I-F",
    "Malagasang I-G",
    "Malagasang II-A",
    "Malagasang II-B",
    "Malagasang II-C",
    "Malagasang II-D",
    "Malagasang II-E",
    "Medicion I-A",
    "Medicion I-B",
    "Medicion I-C",
    "Medicion I-D",
    "Medicion II-A",
    "Medicion II-B",
    "Medicion II-C",
    "Medicion II-D",
    "Medicion II-E",
    "Medicion II-F",
    "Pag-asa I",
    "Pag-asa II",
    "Pag-asa III",
    "Palico I",
    "Palico II",
    "Palico III",
    "Palico IV",
    "Pasong Buaya I",
    "Pasong Buaya II"
  ],
  "Dasmariñas": [
    "Burol I",
    "Burol II",
    "Burol III",
    "Datu Esmael (Bago-a-ingud)",
    "Langkaan I",
    "Langkaan II",
    "Luzviminda I",
    "Luzviminda II",
    "Paliparan I",
    "Paliparan II",
    "Paliparan III",
    "Sabang",
    "Salawag",
    "Salitran I",
    "Salitran II",
    "Salitran III",
    "Salitran IV",
    "San Agustin I",
    "San Agustin II",
    "San Agustin III",
    "San Andres I",
    "San Andres II",
    "San Antonio De Padua I",
    "San Antonio De Padua II",
    "San Dionisio",
    "San Esteban",
    "San Francisco I",
    "San Francisco II",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Lorenzo Ruiz I",
    "San Lorenzo Ruiz II",
    "San Manuel I",
    "San Manuel II",
    "San Miguel",
    "San Nicolas I",
    "San Nicolas II",
    "San Roque",
    "San Simon",
    "Santa Cristina I",
    "Santa Cristina II",
    "Santa Cruz I",
    "Santa Cruz II",
    "Santa Fe",
    "Santa Lucia",
    "Santa Maria",
    "Santo Cristo",
    "Santo Niño I",
    "Santo Niño II",
    "Victoria Reyes",
    "Zone I (Pob.)",
    "Zone II (Pob.)",
    "Zone III (Pob.)",
    "Zone IV (Pob.)"
  ]
};

export const CAVITE_CITIES = Object.keys(CAVITE_CITY_TO_BARANGAYS);

export function getBarangaysForCity(city) {
  return CAVITE_CITY_TO_BARANGAYS[city] || [];
}
